### ISSUE TITLE
get_all_employees hags forever

### ISSUE THREAD

**Issue by TimurNurlygayanov** [smeggingsmegger/PyBambooHR#60]
I'm trying to use get_all_employees method, but it hangs forever:

```
from PyBambooHR.PyBambooHR import PyBambooHR as bamboo

bamboo = bamboo(subdomain='my_company', api_key=bamboo_key, only_current=False)

employees = bamboo.get_all_employees()

print(len(employees))
```

This script hangs forever on line 3.

After several seconds I'm pressing Ctrl+C and getting this traceback

```
Traceback (most recent call last):
  File "exp.py", line 20, in <module>
    employees = bamboo.get_all_employees()
  File "/usr/local/lib/python3.6/dist-packages/PyBambooHR/PyBambooHR.py", line 371, in get_all_employees
    self.employees[uKey] = self.get_employee(uKey, field_list=field_list)
  File "/usr/local/lib/python3.6/dist-packages/PyBambooHR/PyBambooHR.py", line 334, in get_employee
    r = requests.get(url, headers=self.headers, params=payload, auth=(self.api_key, ''))
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1356, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/contrib/pyopenssl.py", line 313, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1716, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
KeyboardInterrupt

```

I'm using Ubuntu 18.04, Python3.8, PyBambooHR==0.8.0 from pip.

**Comment by horida** [comment]
Hi @TimurNurlygayanov 

Could you use a lower timeout as the default of 60 seconds?

```
bamboo = bamboo(subdomain='my_company', api_key=bamboo_key, only_current=False, timeout=10)
```

And see what's the error message?

**Comment by scott-f9** [comment]
Hi @TimurNurlygayanov 

Did you figure out a solution for this?

**Comment by ehbello** [comment]
> Hi @TimurNurlygayanov
> 
> Could you use a lower timeout as the default of 60 seconds?
> 
> ```
> bamboo = bamboo(subdomain='my_company', api_key=bamboo_key, only_current=False, timeout=10)
> ```
> 
> And see what's the error message?

I will answer this.
>     raise HTTPError(http_error_msg, response=self)
>     requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.bamboohr.com/api/gateway.php/<company>/v1/employees/1?fields=address1%2Caddress2%2Cage%2CbestEmail%2Cbirthday%2Ccity%2Ccountry%2CdateOfBirth%2Cdepartment%2Cdivision%2Ceeo%2CemployeeNumber%2CemploymentStatus%2CemploymentHistoryStatus%2Cethnicity%2Cexempt%2CfirstName%2CflsaCode%2CfullName1%2CfullName2%2CfullName3%2CfullName4%2CfullName5%2CdisplayName%2Cgender%2ChireDate%2ChomeEmail%2ChomePhone%2Cid%2CjobTitle%2ClastChanged%2ClastName%2Clocation%2CmaritalStatus%2CmiddleName%2CmobilePhone%2Cnickname%2CpayChangeReason%2CpayGroup%2CpayGroupId%2CpayRate%2CpayRateEffectiveDate%2CpayType%2CpreferredName%2Cssn%2Csin%2Cstate%2CstateCode%2Cstatus%2Csupervisor%2CsupervisorId%2CsupervisorEId%2CterminationDate%2CworkEmail%2CworkPhone%2CworkPhonePlusExtension%2CworkPhoneExtension%2Czipcode%2CphotoUploaded%2CisPhotoUploaded%2CrehireDate%2CadpCompanyCode%2CadpFileNumber%2CstandardHoursPerWeek%2CearningsDate%2CearningsPriorYear%2CbonusDate%2CbonusAmount%2CbonusReason%2CbonusComment%2CcommisionDate%2CcommissionAmount%2CcommissionComment%2CbenefitClassDate%2CbenefitClassClass%2CbenefitClassChangeReason&onlyCurrent=false
